# Dependencies
markdown:         kramdown
highlighter:      rouge
encoding:         utf-8

# Setup
title:            Alireza Bahramali
tagline:          'Personal Webpage'
description:      'abahramali(at)cs.umass.edu'
url:              https://abahramali.github.io/abahramali
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
email:            a[lastname]@cs.umass.edu
author:
  name:           'Alireza Bahramali'
  url:            abahramali.github.io

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
version:            3.4.1
sidebar_home_link:  true
sidebar_blog_link:  '/blog'     # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

github:
  repo:             https://github.com/abahramali

# twitter:            https://twitter.com/chandakyash13
# facebook:           https://www.facebook.com/yashchandak.13
linkedin:           https://www.linkedin.com/in/alireza-bahramali-166ba1122
scholar:            https://scholar.google.com/citations?user=ed6f5vcAAAAJ&hl=en


# Include all files under '_pages' as files in root directory
include: ['_pages']
